### ISSUE TITLE
Cannot write indexes of this type due to unsupported collating sort order

### ISSUE THREAD

**Issue by RickardAngman** [36bits/msmquote#11]
Hi! I'm trying to use your software like this;
- Money Plus Home & Business Sunset, so 17.0.150.3817 on a Windows 11 machine
- Created a spreadsheet at Google https://docs.google.com/spreadsheets/d/1co55-WEyHsec-HAWX-cl3eh8v4NPLf_icrvLtZEAXuM/edit?usp=sharing
- Created a test file for Money called test2.mny with password test. The test file only includes one investment account with one purchase of the ABB stock.

With command
`bin\java -jar .\msmquote-4.1.4.jar test2.mny test 1co55-WEyHsec-HAWX-cl3eh8v4NPLf_icrvLtZEAXuM sample!B1:P16`

I'm getting this output

> 2023-02-06 11:50:44,313 [main] INFO  uk.co.pueblo.msmquote.Update: Version 4.1.4
> 2023-02-06 11:50:44,315 [main] INFO  uk.co.pueblo.msmcore.MsmDb: Creating lock file: C:\Users\ricka\Downloads\msmquote-4.1.4\test2.lrd
> 2023-02-06 11:50:44,316 [main] INFO  uk.co.pueblo.msmcore.MsmDb: Opening Money file: C:\Users\ricka\Downloads\msmquote-4.1.4\test2.mny
> Feb 06, 2023 11:50:44 AM com.healthmarketscience.jackcess.Index setUnsupportedReason
> VARNING: unsupported collating sort order SortOrder[1035(0)] for text index (Db=test2.mny;Table=SEC;Index=1), making read-only
> Feb 06, 2023 11:50:44 AM com.healthmarketscience.jackcess.Index setUnsupportedReason
> VARNING: unsupported collating sort order SortOrder[1035(0)] for text index (Db=test2.mny;Table=SEC;Index=3), making read-only
> Feb 06, 2023 11:50:44 AM com.healthmarketscience.jackcess.Index setUnsupportedReason
> VARNING: unsupported collating sort order SortOrder[1035(0)] for text index (Db=test2.mny;Table=SEC;Index=4), making read-only
> Feb 06, 2023 11:50:44 AM com.healthmarketscience.jackcess.Index setUnsupportedReason
> VARNING: unsupported collating sort order SortOrder[1035(0)] for text index (Db=test2.mny;Table=CRNC;Index=3), making read-only
> Feb 06, 2023 11:50:44 AM com.healthmarketscience.jackcess.Index setUnsupportedReason
> VARNING: unsupported collating sort order SortOrder[1035(0)] for text index (Db=test2.mny;Table=CRNC_EXCHG;Index=0), making read-only
> Feb 06, 2023 11:50:44 AM com.healthmarketscience.jackcess.Index setUnsupportedReason
> VARNING: unsupported collating sort order SortOrder[1035(0)] for text index (Db=test2.mny;Table=CRNC_EXCHG;Index=3), making read-only
> 2023-02-06 11:50:45,281 [main] WARN  uk.co.pueblo.msmcore.MsmInstrument: Optional quote data missing for symbol Atlassian: dBid, dAsk, dDividendYield, dPE
> 2023-02-06 11:50:45,281 [main] WARN  uk.co.pueblo.msmcore.MsmInstrument: Optional default values applied for symbol Atlassian: dDividendYield, dPE
> 2023-02-06 11:50:45,281 [main] INFO  uk.co.pueblo.msmcore.MsmSecurity: Updating quote data for symbol Atlassian, quote type=EQUITY
> 2023-02-06 11:50:45,282 [main] WARN  uk.co.pueblo.msmcore.MsmSecurity: Cannot find symbol Atlassian in SEC table
> 2023-02-06 11:50:45,282 [main] WARN  uk.co.pueblo.msmcore.MsmInstrument: Optional quote data missing for symbol ABB: dBid, dAsk, dDividendYield
> 2023-02-06 11:50:45,282 [main] WARN  uk.co.pueblo.msmcore.MsmInstrument: Optional default values applied for symbol ABB: dDividendYield
> 2023-02-06 11:50:45,282 [main] INFO  uk.co.pueblo.msmcore.MsmSecurity: Updating quote data for symbol ABB, quote type=EQUITY
> 2023-02-06 11:50:45,283 [main] INFO  uk.co.pueblo.msmcore.MsmSecurity: Found symbol ABB in SEC table: sct=1, hsec=5
**> 2023-02-06 11:50:45,287 [main] FATAL uk.co.pueblo.msmquote.Update: java.lang.UnsupportedOperationException: Cannot write indexes of this type due to unsupported collating sort order SortOrder[1035(0)] for text index (Db=test2.mny;Table=SEC;Index=1)**
> 2023-02-06 11:50:45,287 [main] INFO  uk.co.pueblo.msmcore.MsmDb: Closing Money file: test2.mny
> 2023-02-06 11:50:45,287 [main] INFO  uk.co.pueblo.msmquote.Update: Duration: PT0.972557S

**Comment by 36bits** [comment]
Hi,
From Money can you run _File->Repair Money File->Quick File Repair_ and see if this resolves the issue.

**Comment by RickardAngman** [comment]
> Hi, From Money can you run _File->Repair Money File->Quick File Repair_ and see if this resolves the issue.

Just tried that, but didn't help. I have a very small test file, so luckily no error in the file.

**Comment by RickardAngman** [comment]
[test3.zip](https://github.com/36bits/msmquote/files/10668205/test3.zip)
Sharing the test file, test3.mny is the reparied one.

**Comment by 36bits** [comment]
Thanks for that. I see the same errors when I run msmquote  against that file, however if I open the file in Money, then close it again and then run msmquote all is OK.

**Comment by RickardAngman** [comment]
![image](https://user-images.githubusercontent.com/37016770/217073961-8ae034c7-b4b2-41cc-bebf-27c4ed5f2737.png)
Sounds like we might run different versions of Money?

**Comment by 36bits** [comment]
Same version here:
![Screenshot 2023-02-06 201105](https://user-images.githubusercontent.com/23532844/217075032-9280b0b0-61be-42c8-9c2a-3aaab7819cb7.png)

**Comment by RickardAngman** [comment]
Thanks for investigating! Seems like the same version of the software should produce the same files. I'm curious of the word "collating" in the error message if that have something with collation in databases. Perhaps Money adopts to my regional settings of Sweden.

**Comment by RickardAngman** [comment]
Okay, found the problem. When I start a virtual machine with regional settings for UK and open the file and close it. Then your program can update my file. I even got this notification when I hade Money running before changing the settings.
![image](https://user-images.githubusercontent.com/37016770/217085522-6ec1fe72-82e7-443c-bc4f-8a29831073f6.png)
So seems that Money is sensitive to regional settings.

**Comment by 36bits** [comment]
Thanks for confirming this. A search shows that jackcess - the library used by msmquote to access Money files - requires the index text sort order to be 1033 (English US) which is the case when the regional settings are some variant of English. In your file the sort order was set to 1035 (Finnish apparently) and so jackcess - and msmquote - failed.

**Comment by 36bits** [comment]
Closed as requires jackcess to handle index text sort orders other than 1033.

**Comment by 36bits** [comment]
Closed as requires jackcess to handle index text sort orders other than 1033.
