### ISSUE TITLE
how to update OTC quote ?

### ISSUE THREAD

**Issue by camous** [36bits/msmquote#18]
Hello, 

I'm struggling for making OTC quote updated, this one specificaly (https://finance.yahoo.com/quote/0P00000S5C?.tsrc=fin-srch).
I understood that `msquote`  uses the country defined on the quote in msmoney for suffixing the search (eg germany -> .F (francfort)).

But for OTC, there isn't a country. Is there way to make it work ?

**Comment by 36bits** [comment]
You should add this security to your Money file using the symbol `0P00000S5C` and _Country/Region_ set to _United States_. If the base currency of your Money file is US Dollar there is nothing further to do. If it's another currency then you need to remove the Money exchange prefix by following the instructions [here](https://github.com/36bits/msmquote/wiki/How-To#remove-the-money-exchange-prefix-from-an-investment-symbol).

**Comment by camous** [comment]
Thanks for your help. unfortunately I may doing something wrong.
my base currency is in EURO and country FR

1. security initial screen (I created it initially for germany/francfort)
![image](https://github.com/36bits/msmquote/assets/8566299/6023b9ee-05f1-4c29-91b6-9d4fc0ac1c1a)
2. replacing prefix with FR and clicking on comment + NO
![image](https://github.com/36bits/msmquote/assets/8566299/4b3a22fd-8263-4e85-a033-ffdc56110cd9)
3. displaying back DE but expected according to documentation
4. running msquote still pointing to `0P00000S5C.F`
![image](https://github.com/36bits/msmquote/assets/8566299/c7aa237e-f08b-44cd-bd6c-256be001aeb5)

**Comment by 36bits** [comment]
Hi, you need to change the _Pays/Région_ to _États-Unis_ first (and accept the currency change prompt) before you over-type the Money exchange prefix with _FR_.

**Comment by camous** [comment]
ah, was clear for me I have to start the process from US region. 
it worked !

thanks !
